default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mysql
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: devise_demo_development

test:
  <<: *default
  database: devise_demo_test
